### PR TITLE
Support version 3.11

### PR DESCRIPTION
**Pull request by ekohl**
This version is already being shipped by Katello 4.1 and should be supported.

### CODE REVIEW

**Comment by ekohl** [comment]
It fails because 2to3 is incompatible with the Django version. I'm surprised repoclosure didn't catch this but it's probably a limitation of RPM.

**Comment by ekohl** [comment]
Not for us, but do we have a way to uninstall it for users?

**Comment by evgeni** [comment]
Uh, no, probably not. Good point.

**Comment by ekohl** [comment]
https://github.com/pulp/pulp-2to3-migration/pull/381 should unpin it again.

**Review by ehelms — APPROVED** [review]

**Comment by ekohl** [comment]
@evgeni do you think we can include such a PR in the update procedure? https://github.com/theforeman/tool_belt/blob/master/procedures/pulpcore/update.md.erb does have a `Update to a new pulpcore release` section.

**Pull request merged**
