### PR TITLE
Add Puppet 8 support

### PR DESCRIPTION
**Pull request by bastelfreak**
also contains #296

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
It fails with:
```
Error: Undefined variable 'fqdn' (file: /etc/puppetlabs/puppet/hiera.yaml, line: 6) on node centos8-64.example.com
```

Perhaps https://github.com/theforeman/puppet-pulpcore/pull/298 will fix that, but the error is vague.

**Comment by ekohl** [comment]
Still the same error. I really wonder where it comes from. I wonder if it's the Hiera 3 format. https://github.com/voxpupuli/beaker-hiera/pull/17 should deal with that.

**Comment by ekohl** [comment]
Trivial rebase now that we've updated the gems to support Puppet 8 testing in CI. I've also opened https://github.com/theforeman/puppet-pulpcore/pull/312 to test together with https://github.com/voxpupuli/beaker-hiera/pull/17.

**Comment by ekohl** [comment]
Still failing and I'm pretty sure https://github.com/voxpupuli/voxpupuli-acceptance/pull/74 should help.

**Review by ekohl — APPROVED** [review]
If CI is green.

**Comment by bastelfreak** [comment]
@ekohl looks goodm CI passed

**Pull request merged**
