### PR TITLE
Fixes #30133 - Install python3-subscription-manager-rhsm

### PR DESCRIPTION
**Pull request by sjha4**
Install rhsm package for el7. Dependent on https://github.com/theforeman/foreman-packaging/pull/5363

### CODE REVIEW

**Comment by jlsherrill** [comment]
Part of the problem with defining it in packaging is that this is an optional dependency to the certguard plugin.  One that katello needs for the flavor of certguard its using.  Thats why i think its better to be done in puppet (but i'd probably suggest in puppet-foreman_proxy_content?)

**Comment by ehelms** [comment]
I think this makes sense here, although should it be here instead? https://github.com/theforeman/puppet-pulpcore/blob/master/manifests/plugin/certguard.pp

Doing this in packaging, is tricky as we'd have to tie it to the meta-package since we cannot tie it to the Pulp packages.

**Comment by wbclark** [comment]
Thanks for the update, @sjha4 .

It looks like the test failure is due to the fact that the package is not yet available:

```
[root@centos7-64-1 ~]# yum install python3-subscription-manager-rhsm
Loaded plugins: fastestmirror
Repository 'pulpcore' is missing name in configuration, using id
Loading mirror speeds from cached hostfile
epel/x86_64/metalink                                     |  18 kB     00:00     
 * base: packages.oit.ncsu.edu
 * centos-sclo-rh: ewr.edge.kernel.org
 * epel: packages.oit.ncsu.edu
 * extras: distro.ibiblio.org
 * updates: repos-va.psychz.net
base                                                     | 3.6 kB     00:00     
centos-sclo-rh                                           | 3.0 kB     00:00     
epel                                                     | 5.3 kB     00:00     
extras                                                   | 2.9 kB     00:00     
pulpcore                                                 | 3.6 kB     00:00     
puppet6                                                                                                                                                                                                                                                            | 2.5 kB  00:00:00     
updates                                                                                                                                                                                                                                                            | 2.9 kB  00:00:00     
(1/4): epel/x86_64/updateinfo                                                                                                                                                                                                                                      | 1.0 MB  00:00:00     
(2/4): puppet6/x86_64/primary_db                                                                                                                                                                                                                                   | 296 kB  00:00:00     
(3/4): epel/x86_64/primary_db                                                                                                                                                                                                                                      | 6.8 MB  00:00:01     
(4/4): updates/7/x86_64/primary_db                                                                                                                                                                                                                                 | 2.1 MB  00:00:02     
No package python3-subscription-manager-rhsm available.
Error: Nothing to do
[root@centos7-64-1 ~]# yum search rhsm
Loaded plugins: fastestmirror
Repository 'pulpcore' is missing name in configuration, using id
Loading mirror speeds from cached hostfile
 * base: packages.oit.ncsu.edu
 * centos-sclo-rh: ftp.osuosl.org
 * epel: mirror.vcu.edu
 * extras: distro.ibiblio.org
 * updates: mirror.ilumno.com
=================================================================================================================================== N/S matched: rhsm ====================================================================================================================================
librhsm-devel.x86_64 : Development libraries and header files for librhsm
librhsm.x86_64 : Red Hat Subscription Manager library
python-rhsm.x86_64 : A Python library to communicate with a Red Hat Unified Entitlement Platform
python-rhsm-certificates.x86_64 : Certificates required to communicate with a Red Hat Unified Entitlement Platform
rhsm-gtk.x86_64 : GTK+ widgets used by subscription-manager-gui and initial_setup
subscription-manager-rhsm.x86_64 : A Python library to communicate with a Red Hat Unified Entitlement Platform
subscription-manager-rhsm-certificates.x86_64 : Certificates required to communicate with a Red Hat Unified Entitlement Platform

  Name and summary matches only, use "search all" for everything.
[root@centos7-64-1 ~]# 
```

While we are waiting for that, could you also update `spec/classes/plugin_certguard_spec.rb` to see that the package is declared on EL7?

**Comment by jlsherrill** [comment]
Package should be available the next time the pipeline passes, eric and I are working on it

**Comment by jlsherrill** [comment]
Now available in nightly: https://fedorapeople.org/groups/katello/releases/yum/nightly/pulpcore/el7/x86_64/

doesn't look like i have perms ot restart the travis test

**Pull request merged**
