### PR TITLE
Fixes #32552 - run db migrate before collect static

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by wbclark** [comment]
Should we hold this open while waiting on https://pulp.plan.io/issues/8712 or go ahead and close it?

**Comment by ekohl** [comment]
I think it depends on how urgent we think this is. I'd prefer a proper backport and close this without merging because this feels like a workaround. However, if it's urgent and can't wait for upstream then we can talk about merging this.

**Comment by ekohl** [comment]
Given it's now merged, I think this can be closed. Right @jlsherrill?

**Comment by jlsherrill** [comment]
yes, closing now!

**Pull request closed without merging**
