### PR TITLE
Drop Puppet 5 support

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Review by ehelms — APPROVED** [review]

**Comment by ehelms** [comment]
This needs a rebase

**Comment by ekohl** [comment]
Rebased and :green_apple:

**Comment by ekohl** [comment]
Marking as a draft. We should first get all 3.14 things merged & released. Then it can be backported to Katello 4.1.

**Comment by ehelms** [comment]
Needs https://github.com/theforeman/puppet-pulpcore/pull/221

**Pull request merged**
