### PR TITLE
Clean up HTTPS Vhost when no longer used

### PR DESCRIPTION
**Pull request by wbclark**
https://github.com/theforeman/puppet-foreman_proxy_content/pull/390 transitions to deploying the Pulpcore Vhost within puppet-FPC

This PR ensures the Vhost that was previously configured here is cleaned up on upgrades

### CODE REVIEW

**Comment by wbclark** [comment]
/sigh

TIL `rake validate` does not include `rake lint`

**Review by ekohl — COMMENTED** [review]
Normally we rely on Apache to purge configs. I'm not sure if we want to support this. If we do, then we should also purge the HTTP vhost.

**Comment by wbclark** [comment]
> Normally we rely on Apache to purge configs.

Interesting. Could you point me towards where I could read about this?

**Comment by ekohl** [comment]
https://forge.puppet.com/modules/puppetlabs/apache/reference#purge_configs & https://forge.puppet.com/modules/puppetlabs/apache/reference#purge_vhost_dir

**Comment by wbclark** [comment]
`purge_configs` looks `true` by default so I'll close this as it should not be needed. Thanks!

**Pull request closed without merging**
