### PR TITLE
Support Puppet 7

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by wbclark** [comment]
Re-running tests. I expect some will be fixed by https://github.com/theforeman/puppet-pulpcore/commit/30d4ecacdc4a98db88e08c2efb5a387b31e7aa53 while others would still fail due to `::systemd::systemctl::daemon_reload` in puppet-redis

**Comment by ekohl** [comment]
Rebased which also happens to trigger tests as well.

**Comment by ekohl** [comment]
Rebased again, let's see if the tests do pass now or if we really did hit a bug.

**Comment by ekohl** [comment]
It does look persistent.

**Review by ehelms — APPROVED** [review]

**Pull request merged**
