### PR TITLE
Pulpcore logging format to include correlation id.

### PR DESCRIPTION
**Pull request by jjeffers**

### CODE REVIEW

**Comment by jlsherrill** [comment]
This looks good to me, just need tests to be fixed

**Review by ekohl — COMMENTED** [review]
Do we only have correlation IDs in the API service? Is this also something that should be logged in workers?

**Comment by jlsherrill** [comment]
According to @daviddavis the workers are passed a correlation id but log it by default, no need for special configuration

**Comment by daviddavis** [comment]
> Do we only have correlation IDs in the API service? Is this also something that should be logged in workers?

Assuming that you're using the default for LOGGING, [it should include the correlation id in the django logs](https://github.com/pulp/pulpcore/blob/00497f89e06e50a1b15854a9917f7bab1848a40f/pulpcore/app/settings.py#L195) which applies to the workers. This line here is to configure gunicorn to also output the correlation id.

**Comment by ekohl** [comment]
Ok, that's good. I also don't think content has correlation IDs. Correct?

**Comment by daviddavis** [comment]
That's correct: the content app does not support correlation id. If that's something you all need, I can take a look.

**Comment by ekohl** [comment]
I don't think so but I would like to make sure this PR covers everything we need. I'd like to avoid doing multiple PRs, each for a single service.

**Comment by jjeffers** [comment]
@ekohl @ehelms @jlsherrill anything else that should be changed for this PR?

**Review by jlsherrill — APPROVED** [review]

**Comment by jlsherrill** [comment]
@ekohl okay to merge?

**Review by ehelms — APPROVED** [review]

**Pull request merged**
